# Generated by Django 2.2.4 on 2020-06-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200601_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
