# Generated by Django 2.2.4 on 2020-06-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200601_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('course', 'class_id', 'teacher_id')},
        ),
    ]
