# Generated by Django 2.2.4 on 2020-06-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200601_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('course', 'class_id', 'teacher')},
        ),
    ]
