# Generated by Django 2.2.4 on 2020-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200601_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
    ]
